
version: '3'

networks:
  helpme_network:
    driver: bridge    

services:

#docker-compose -f docker-compose-helpme.yml up helpme_postgres_local
  helpme_postgres_local:
    restart: always
    container_name: postgres-helpme-local
    image: postgres:12.2-alpine
    ports:
      - 5234:5234
    networks:
      - helpme_network
    environment:
      - POSTGRES_DB=helpme
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123@mudar

  #docker-compose -f docker-compose-helpme.yml up helpme_pgadmin
  helpme_pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: helpme-pgadmin
    ports:
      - 15234:80
    networks:
      - helpme_network
    environment:
      - PGADMIN_DEFAULT_PASSWORD=p0stgr3s
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
    depends_on:
      - helpme_postgres_local