CREATE TABLE IF NOT EXISTS public.pessoa
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nome character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    senha character varying(255) COLLATE pg_catalog."default",
    cpf character varying(255) COLLATE pg_catalog."default",
    data_criacao date,
    dtype character varying(31) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pessoa_pkey PRIMARY KEY (id),
    CONSTRAINT uk_mc87q8fpvldpdyfo9o5633o5l UNIQUE (email),
    CONSTRAINT uk_nlwiu48rutiltbnjle59krljo UNIQUE (cpf)
)