CREATE TABLE IF NOT EXISTS public.chamado
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    prioridade integer,
    titulo character varying(255) COLLATE pg_catalog."default",
    observacoes character varying(255) COLLATE pg_catalog."default",
    status integer,
    cliente_id integer,
    tecnico_id integer,
    data_abertura date,
    data_fechamento date,
    CONSTRAINT chamado_pkey PRIMARY KEY (id),
    CONSTRAINT fkivlss0iq4e3dcjqwgfar8i77a FOREIGN KEY (cliente_id)
        REFERENCES public.pessoa (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkkc34p1kfv0acpiymukv930dd9 FOREIGN KEY (tecnico_id)
        REFERENCES public.pessoa (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
